### PR TITLE
Front end/003/data approval

### LINKED ISSUE #30: Bug/004/Get reference in new knowledge data
image
- Lấy được data sao lại để successAlert thế kia hả 👎

### LINKED ISSUE #31: Bug/005/Button + Synonym ở phần thêm synonym cho từ
image
Thay đổi tên nút đi như kiểu Apply synonym set và thay icon đi tra cái icon apply xem

### LINKED ISSUE #32: Bug/006/SuccessAlert cho phần new knowledge data
Chỉ hiện success alert khi mà gửi form tổng thôi. Mấy cái gọi API linh tinh thì không hiện chả để làm gì 
@Kirisaki124

### LINKED ISSUE #33: Bug/007/Create Button ở phần generate question
image
Khi mà generate lần 1 thì nó hiện View question đúng không. bấm vào Modal thì phải phần nút Create thành SAVE chứ với cả thêm icon save vào

### LINKED ISSUE #34: Bug/008/When errorList state has a list of error -> cant send form
image
Trong phần new knowledge data khi mà submit form lỗi thì phải xóa errorList state thì mới gửi form tiếp được 
=> Đéo ai check như thế ???

### LINKED ISSUE #35: Bug/009/Add Synonym for specific word
image

- Phần thêm synonym cho từ theo a dũng nói thì phải làm thêm 1 chức năng là khi tokenize word ra thì có thể sẽ có thể không theo ý mình. Như trên hình có từ Trên Messenger bị tách ra. Nhưng mà mình lại muốn add synonym cả hẳn cái cụm từ Trên Messenger thì làm sao ? 

=> Anh Dũng bảo phải làm thêm 1 cái nút gì gì đó để ghép cái từ 'messenger' với từ 'Trên' thành 1 từ 'Trên messenger'

### LINKED ISSUE #36: Bug/010/Loading title for knowledge data list
image

- Nhìn ảnh là biết đấy 👎

### LINKED ISSUE #37: Bug/011/SuccessfullAlert display wrong when tokenizing "Raw data"
image

- Nhìn ảnh là biết rồi đấy

### LINKED ISSUE #38: Bug/012/In Edit Knowledge Data When add more synonym for specific word
image

- Khi mà vào 1 knowledge data bất kì rồi thêm bộ từ đồng nghĩa cho 1 từ bất kì xong rồi submit form thì hiện ra lỗi

### LINKED ISSUE #39: Bug/013/Name of the button 'Edit' in Edit Knowledge Data
image
Sửa lại tên đi cho thêm cái icon vào

### PR DESCRIPTION
**Pull request by Kirisaki124**

### CODE REVIEW

File: src/modules/contributor/components/knowledgeDataComponent/RawData.js [hunk 1]
```diff
@@ -132,9 +133,24 @@ class RawData extends Component {
                   if (ner.index === index) flag = true;
                 });
                 let className = 'mr-1 word-box ';
-                if (this.props.hoverWord === data.value) {
-                  className += 'hover-word ';
-                }
+
+                let hoverWordList = this.props.hoverWord.split(" ")
+
+                // if (hoverWordList[0] === data.value) {
```
Comment (LethDz) [inline src/modules/contributor/components/knowledgeDataComponent/RawData.js]: Xóa đê 👎

**Review by LethDz — CHANGES_REQUESTED** [review]

**Review by LethDz — APPROVED** [review]
oke 👍
